# Device-only iOS CMake toolchain for the OpenMW iOS port kit.
# Use with: cmake -G Xcode -DCMAKE_TOOLCHAIN_FILE=.../iOS-device-toolchain.cmake

set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_OSX_SYSROOT iphoneos CACHE STRING "Build for physical iOS devices" FORCE)
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "iOS device architecture" FORCE)
set(CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH NO CACHE STRING "Build all requested architectures" FORCE)

if(NOT DEFINED CMAKE_OSX_DEPLOYMENT_TARGET)
  set(CMAKE_OSX_DEPLOYMENT_TARGET 15.0 CACHE STRING "Minimum supported iOS version" FORCE)
endif()

set(CMAKE_POSITION_INDEPENDENT_CODE ON CACHE BOOL "Required for iOS static archives" FORCE)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
